version: '3.8'

services:
  frontend:
    image: ruinow/inkflow-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: ruinow/inkflow-backend:latest
    environment:
      - DATABASE_URL=postgresql+asyncpg://inkflow:${POSTGRES_PASSWORD}@postgres:5432/inkflow
      - SECRET_KEY=${SECRET_KEY}
      - KIMI_API_KEY=${KIMI_API_KEY}
      - ALLOWED_ORIGINS=*
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=inkflow
      - POSTGRES_USER=inkflow
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: