services:
  inkflow_frontend:
    container_name: inkflow-frontend-container
    image: ruinow/inkflow-frontend:latest
    ports:
      - "3030:80"
    depends_on:
      - backend

  inkflow_backend:
    container_name: inkflow_backend_container
    image: ruinow/inkflow-backend:latest
    ports:
      - "8000:8000"
    env_file: .env