version: '3.8'

services:
  inkflow_frontend:
    container_name: inkflow-frontend-container
    image: ruinow/inkflow-frontend:latest
    ports:
      - "3030:3000"
    env_file: .env
    depends_on:
      - inkflow_backend
    networks:
      - default-network

  inkflow_backend:
    container_name: inkflow-backend-container
    image: ruinow/inkflow-backend:latest
    ports:
      - "8000:8000"
    env_file: .env
    user: root  # 临时以root用户运行解决权限问题
    networks:
      - default-network

networks:
  default-network:
    external: true