version: '3.8'

services:
  inkflow_frontend:
    container_name: inkflow-frontend-container
    image: ruinow/inkflow-frontend:latest
    ports:
      - "3030:3000"
    environment:
      - VITE_API_BASE_URL=${API_BASE_URL:-http://localhost:8000/api/v1}
    depends_on:
      - inkflow_backend
    networks:
      - default-network

  inkflow_backend:
    container_name: inkflow-backend-container
    image: ruinow/inkflow-backend:latest
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - default-network

networks:
  default-network:
    external: true