version: '3.8'

services:
  frontend:
    image: ruinow/inkflow-frontend:latest
    ports:
      - "3030:80"
    depends_on:
      - backend

  backend:
    image: ruinow/inkflow-backend:latest
    ports:
      - "8000:8000"
    env_file: .env