"""添加任务管理系统 - task_id机制支持

Revision ID: 6e4bc2f8d7b5
Revises: 316cc97feb71
Create Date: 2025-09-22 09:33:51.845588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4bc2f8d7b5'
down_revision: Union[str, Sequence[str], None] = '316cc97feb71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('FIRST_CHAPTER_GENERATION', 'CHAPTER_GENERATION', 'NOVEL_OUTLINE_GENERATION', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_tasks_id'), 'generation_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_generation_tasks_task_id'), 'generation_tasks', ['task_id'], unique=True)
    op.alter_column('chapters', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('chapters_novel_id_chapter_number_key'), 'chapters', type_='unique')
    op.drop_index(op.f('ix_chapters_novel_id'), table_name='chapters')
    op.drop_column('chapters', 'word_count')
    op.drop_index(op.f('ix_novels_user_id'), table_name='novels')
    op.create_index(op.f('ix_novels_title'), 'novels', ['title'], unique=False)
    op.create_index(op.f('ix_options_id'), 'options', ['id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_options_id'), table_name='options')
    op.drop_index(op.f('ix_novels_title'), table_name='novels')
    op.create_index(op.f('ix_novels_user_id'), 'novels', ['user_id'], unique=False)
    op.add_column('chapters', sa.Column('word_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_chapters_novel_id'), 'chapters', ['novel_id'], unique=False)
    op.create_unique_constraint(op.f('chapters_novel_id_chapter_number_key'), 'chapters', ['novel_id', 'chapter_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('chapters', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_generation_tasks_task_id'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_id'), table_name='generation_tasks')
    op.drop_table('generation_tasks')
    # ### end Alembic commands ###
