"""Add chapters, options and user_choices tables

Revision ID: e23315eafbc7
Revises: 013fbe23817b
Create Date: 2025-09-14 22:08:01.895279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e23315eafbc7'
down_revision: Union[str, Sequence[str], None] = '013fbe23817b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_choices_id'), 'user_choices', ['id'], unique=False)
    op.alter_column('chapters', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.add_column('options', sa.Column('option_order', sa.Integer(), nullable=False))
    op.add_column('options', sa.Column('option_text', sa.Text(), nullable=False))
    op.add_column('options', sa.Column('impact_description', sa.Text(), nullable=True))
    op.drop_constraint('options_novel_id_fkey', 'options', type_='foreignkey')
    op.drop_column('options', 'novel_id')
    op.drop_column('options', 'description')
    op.drop_column('options', 'option_number')
    op.drop_column('options', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('options', sa.Column('option_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('options', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('options', sa.Column('novel_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('options_novel_id_fkey', 'options', 'novels', ['novel_id'], ['id'])
    op.drop_column('options', 'impact_description')
    op.drop_column('options', 'option_text')
    op.drop_column('options', 'option_order')
    op.alter_column('chapters', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_index(op.f('ix_user_choices_id'), table_name='user_choices')
    op.drop_table('user_choices')
    # ### end Alembic commands ###
