"""优化任务表：移除实时更新字段，简化为核心业务字段

Revision ID: e4487f02eef6
Revises: 6e4bc2f8d7b5
Create Date: 2025-09-23 14:17:36.899261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4487f02eef6'
down_revision: Union[str, Sequence[str], None] = '6e4bc2f8d7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_tasks', 'total_steps')
    op.drop_column('generation_tasks', 'updated_at')
    op.drop_column('generation_tasks', 'progress_percentage')
    op.drop_column('generation_tasks', 'started_at')
    op.drop_column('generation_tasks', 'current_step')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.add_column('generation_tasks', sa.Column('current_step', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('generation_tasks', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('generation_tasks', sa.Column('progress_percentage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('generation_tasks', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('generation_tasks', sa.Column('total_steps', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
